export const countryMap: Record<string, string> = {
    "Andorra": "ad",
    "United Arab Emirates": "ae",
    "Afghanistan": "af",
    "Antigua and Barbuda": "ag",
    "Anguilla": "ai",
    "Albania": "al",
    "Armenia": "am",
    "Netherlands Antilles": "an",
    "United States": "us",
    "Country (MT)": "mt",
    "Country (CM)": "cm",
    "Country (NP)": "np",
    "Country (US)": "us",
    "Country (CA)": "ca",
    "Country (GB)": "gb",
    "Country (AU)": "au",
    "Country (DE)": "de",
    "Country (FR)": "fr",
    "Country (IT)": "it",
    "Country (ES)": "es",
    "Country (BR)": "br",
    "Country (IN)": "in",
    "Country (JP)": "jp",
    "Country (KR)": "kr",
    "Country (CN)": "cn",
    "Country (RU)": "ru",
    "Country (ZA)": "za",
    "Country (MX)": "mx",
    "Country (NG)": "ng",
    "Country (PH)": "ph",
    "Country (TH)": "th",
    "Country (ID)": "id",
    "Country (MY)": "my",
    "Country (SG)": "sg",
    "Country (VN)": "vn",
    "Country (AE)": "ae",
    "Country (SA)": "sa",
    "Country (EG)": "eg",
    "Country (IL)": "il",
    "Country (TR)": "tr",
    "Country (PK)": "pk",
    "Country (BD)": "bd",
    "Country (LK)": "lk",
    "Country (MM)": "mm",
    "Country (KH)": "kh",
    "Angola": "ao",
    "Antarctica": "aq",
    "Argentina": "ar",
    "American Samoa": "as",
    "Austria": "at",
    "Australia": "au",
    "Australian Aboriginal": "",
    "Torres Strait Islands": "",
    "Australian Capital Territory": "au-act",
    "New South Wales": "au-nsw",
    "Northern Territory": "au-nt",
    "Queensland": "au-qld",
    "South Australia": "au-sa",
    "Tasmania": "au-tas",
    "Victoria": "au-vic",
    "Western Australia": "au-wa",
    "Aruba": "aw",
    "Åland Islands": "ax",
    "Azerbaijan": "az",
    "Bosnia and Herzegovina": "ba",
    "Barbados": "bb",
    "Bangladesh": "bd",
    "Belgium": "be",
    "Burkina Faso": "bf",
    "Bulgaria": "bg",
    "Bahrain": "bh",
    "Burundi": "bi",
    "Benin": "bj",
    "Saint Barthélemy": "bl",
    "Bermuda": "bm",
    "Brunei": "bn",
    "Bolivia": "bo",
    "Bonaire": "bq-bo",
    "Saba": "bq-sa",
    "Sint Eustatius": "bq-se",
    "Brazil": "br",
    "Bahamas": "bs",
    "Bhutan": "bt",
    "Bouvet Island": "bv",
    "Botswana": "bw",
    "Belarus": "by",
    "Belize": "bz",
    "Canada": "ca",
    "British Columbia": "ca-bc",
    "Quebec": "ca-qc",
    "Cocos (Keeling) Islands": "cc",
    "Congo, Democratic Republic of the": "cd",
    "Central African Republic": "cf",
    "Congo": "cg",
    "Switzerland": "ch",
    "Grisons": "ch-gr",
    "Ivory Coast": "ci",
    "Cook Islands": "ck",
    "Chile": "cl",
    "Cameroon": "cm",
    "China": "cn",
    "Xinjiang": "cn-xj",
    "Colombia": "co",
    "Sark": "cq",
    "Costa Rica": "cr",
    "Cuba": "cu",
    "Cabo Verde": "cv",
    "Curaçao": "cw",
    "Christmas Island": "cx",
    "Cyprus": "cy",
    "Czechia": "cz",
    "Germany": "de",
    "Djibouti": "dj",
    "Denmark": "dk",
    "Dominica": "dm",
    "Dominican Republic": "do",
    "Algeria": "dz",
    "Earth": "",
    "East African Federation": "",
    "Easter Island": "",
    "Ecuador": "ec",
    "Galápagos": "ec-w",
    "Estonia": "ee",
    "Egypt": "eg",
    "Western Sahara": "eh",
    "Eritrea": "er",
    "Spain": "es",
    "Aragon": "es-ar",
    "Ceuta": "es",
    "Canary Islands": "es-cn",
    "Catalonia": "es-ct",
    "Galicia": "es-ga",
    "Balearic Islands": "es-ib",
    "Melilla": "es-ml",
    "Basque Country": "es-pv",
    "Ethiopia": "et",
    "Afar": "et-af",
    "Amhara": "et-am",
    "Benishangul-Gumuz": "et-be",
    "Gambela": "et-ga",
    "Harari": "et-ha",
    "Oromia": "et-or",
    "Sidama": "et-si",
    "Southern Nations, Nationalities, and Peoples' Region": "et-sn",
    "Somali": "et-so",
    "South West Region": "et-sw",
    "Tigray": "et-ti",
    "European Union": "eu",
    "Ewe": "",
    "Finland": "fi",
    "Fiji": "fj",
    "Falkland Islands (Malvinas)": "fk",
    "Micronesia": "fm",
    "Faroe Islands": "fo",
    "France": "fr",
    "Corsica": "fr-20r",
    "Brittany": "fr-bre",
    "Clipperton Island": "fr-cp",
    "Gabon": "ga",
    "United Kingdom": "gb",
    "Cornwall": "gb-con",
    "England": "gb-eng",
    "Northern Ireland": "gb-nir",
    "Orkney": "gb-ork",
    "Scotland": "gb-sct",
    "Wales": "gb-wls",
    "Grenada": "gd",
    "Georgia": "us-ga",
    "Abkhazia": "ge-ab",
    "French Guiana": "gf",
    "Guernsey": "gg",
    "Ghana": "gh",
    "Gibraltar": "gi",
    "Greenland": "gl",
    "Gambia": "gm",
    "Guinea": "gn",
    "Guadeloupe": "gp",
    "Equatorial Guinea": "gq",
    "Greece": "gr",
    "South Georgia and the South Sandwich Islands": "gs",
    "Guatemala": "gt",
    "Guam": "gu",
    "Guarani": "",
    "Guinea-Bissau": "gw",
    "Guyana": "gy",
    "Hausa": "",
    "Hong Kong": "hk",
    "Hmong": "",
    "Heard Island and McDonald Islands": "hm",
    "Honduras": "hn",
    "Croatia": "hr",
    "Haiti": "ht",
    "Hungary": "hu",
    "Indonesia": "id",
    "West Java": "id-jb",
    "Central Java": "id-jt",
    "Ireland": "ie",
    "Israel": "il",
    "Isle of Man": "im",
    "India": "in",
    "Assam": "in-as",
    "Gujarat": "in-gj",
    "Karnataka": "in-ka",
    "Manipur": "in-mn",
    "Mizoram": "in-mz",
    "Odisha": "in-or",
    "Telangana": "in-tg",
    "Tamil Nadu": "in-tn",
    "British Indian Ocean Territory": "io",
    "Iraq": "iq",
    "Kurdistan": "iq-kr",
    "Iran": "ir",
    "Iceland": "is",
    "Italy": "it",
    "Piedmont": "it-21",
    "Aosta Valley": "it-23",
    "Lombardy": "it-25",
    "Trentino-Alto Adige": "it-32",
    "Veneto": "it-34",
    "Friuli Venezia Giulia": "it-36",
    "Liguria": "it-42",
    "Emilia-Romagna": "it-45",
    "Tuscany": "it-52",
    "Umbria": "it-55",
    "Marche": "it-57",
    "Lazio": "it-62",
    "Abruzzo": "it-65",
    "Molise": "it-67",
    "Campania": "it-72",
    "Apulia": "it-75",
    "Basilicata": "it-77",
    "Calabria": "it-78",
    "Sicily": "it-82",
    "Sardinia": "it-88",
    "Jersey": "je",
    "Jamaica": "jm",
    "Jordan": "jo",
    "Japan": "jp",
    "Kanuri": "",
    "Kenya": "ke",
    "Kyrgyzstan": "kg",
    "Cambodia": "kh",
    "Kiribati": "ki",
    "Kikuyu": "",
    "Comoros": "km",
    "Saint Kitts and Nevis": "kn",
    "Kongo": "",
    "North Korea": "kp",
    "South Korea": "kr",
    "Kuwait": "kw",
    "Cayman Islands": "ky",
    "Kazakhstan": "kz",
    "Laos": "la",
    "Lebanon": "lb",
    "Saint Lucia": "lc",
    "Liechtenstein": "li",
    "Sri Lanka": "lk",
    "Liberia": "lr",
    "Lesotho": "ls",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Latvia": "lv",
    "Libya": "ly",
    "Morocco": "ma",
    "Malayali": "",
    "Maori": "",
    "Mars": "ma",
    "Monaco": "mc",
    "Moldova": "md",
    "Montenegro": "me",
    "Saint-Martin": "mf",
    "Madagascar": "mg",
    "Marshall Islands": "mh",
    "North Macedonia": "mk",
    "Mali": "ml",
    "Myanmar": "mm",
    "Mongolia": "mn",
    "Macao": "mo",
    "Northern Mariana Islands": "mp",
    "Martinique": "mq",
    "Mauritania": "mr",
    "Montserrat": "ms",
    "Malta": "mt",
    "Mauritius": "mu",
    "Maldives": "mv",
    "Malawi": "mw",
    "Mexico": "mx",
    "Malaysia": "my",
    "Mozambique": "mz",
    "Namibia": "na",
    "New Caledonia": "nc",
    "NATO": "",
    "Niger": "ne",
    "Norfolk Island": "nf",
    "Nigeria": "ng",
    "Nicaragua": "ni",
    "Netherlands": "nl",
    "Friesland": "nl-fr",
    "Norway": "no",
    "Northern Cyprus": "",
    "Nepal": "np",
    "Nauru": "nr",
    "Niue": "nu",
    "New Zealand": "nz",
    "Occitania": "",
    "Olympics": "",
    "Oman": "om",
    "Otomi": "",
    "Panama": "pa",
    "Peru": "pe",
    "French Polynesia": "pf",
    "Papua New Guinea": "pg",
    "Philippines": "ph",
    "Pakistan": "pk",
    "Azad Kashmir": "pk-jk",
    "Sindh": "pk-sd",
    "Poland": "pl",
    "Saint Pierre and Miquelon": "pm",
    "Pitcairn Islands": "pn",
    "Puerto Rico": "pr",
    "Palestine": "ps",
    "Azores": "pt-20",
    "Madeira": "pt-30",
    "Portugal": "pt",
    "Palau": "pw",
    "Paraguay": "py",
    "Qatar": "qa",
    "Quechua": "",
    "Réunion": "re",
    "Romania": "ro",
    "Serbia": "rs",
    "Russia": "ru",
    "Bashkortostan": "ru-ba",
    "Chechnya": "ru-ce",
    "Chuvashia": "ru-cu",
    "Dagestan": "ru-da",
    "Donetsk People's Republic": "ru-dpr",
    "Komi Republic": "ru-ko",
    "Luhansk People's Republic": "ru-lpr",
    "Tatarstan": "ru-ta",
    "Udmurtia": "ru-ud",
    "Rwanda": "rw",
    "Saudi Arabia": "sa",
    "Sami": "",
    "Solomon Islands": "sb",
    "Seychelles": "sc",
    "Sudan": "sd",
    "Sweden": "se",
    "Singapore": "sg",
    "Ascension Island": "sh-ac",
    "Saint Helena": "sh-hl",
    "Tristan da Cunha": "sh-ta",
    "Slovenia": "si",
    "Svalbard and Jan Mayen": "sj",
    "Slovakia": "sk",
    "Sierra Leone": "sl",
    "San Marino": "sm",
    "Senegal": "sn",
    "Somalia": "so",
    "Somaliland": "",
    "South Ossetia": "",
    "Soviet Union": "su",
    "Suriname": "sr",
    "South Sudan": "ss",
    "São Tomé and Príncipe": "st",
    "El Salvador": "sv",
    "Sint Maarten": "sx",
    "Syria": "sy",
    "Eswatini": "sz",
    "Turks and Caicos Islands": "tc",
    "Chad": "td",
    "French Southern Territories": "tf",
    "Togo": "tg",
    "Thailand": "th",
    "Tibet": "",
    "Tajikistan": "tj",
    "Tokelau": "tk",
    "Timor-Leste": "tl",
    "Turkmenistan": "tm",
    "Tunisia": "tn",
    "Tonga": "to",
    "Turkey": "tr",
    "Transnistria": "",
    "Trinidad and Tobago": "tt",
    "Tuvalu": "tv",
    "Taiwan": "tw",
    "Tanzania": "tz",
    "Ukraine": "ua",
    "Uganda": "ug",
    "United Nations": "un",
    "United States of America": "us",
    "Alaska": "us-ak",
    "Alabama": "us-al",
    "Arkansas": "us-ar",
    "Arizona": "us-az",
    "California": "us-ca",
    "Colorado": "us-co",
    "District of Columbia": "us-dc",
    "Florida": "us-fl",
    "Hawaii": "us-hi",
    "Indiana": "us-in",
    "Maryland": "us-md",
    "Missouri": "us-mo",
    "Mississippi": "us-ms",
    "North Carolina": "us-nc",
    "New Mexico": "us-nm",
    "Oregon": "us-or",
    "Rhode Island": "us-ri",
    "South Carolina": "us-sc",
    "Tennessee": "us-tn",
    "Texas": "us-tx",
    "Washington": "us-wa",
    "Wisconsin": "us-wi",
    "Wyoming": "us-wy",
    "Betsy Ross": "",
    "Confederate battle": "",
    "United States Minor Outlying Islands": "um",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Holy See (Vatican)": "va",
    "Saint Vincent and the Grenadines": "vc",
    "Venezuela": "ve",
    "Virgin Islands (British)": "vg",
    "Virgin Islands (U.S.)": "vi",
    "Vietnam": "vn",
    "Vanuatu": "vu",
    "Wallis and Futuna": "wf",
    "Wiphala": "",
    "Samoa": "ws",
    "Kosovo": "xk",
    "<Placeholder>": "",
    "Yemen": "ye",
    "Yorubaland": "",
    "Mayotte": "yt",
    "Yugoslavia": "yu",
    "South Africa": "za",
    "Zambia": "zm",
    "Zimbabwe": "zw",
    
};
